### ISSUE TITLE
Keycloak Admin.v2 - Minified React error #306 when opening a client

### ISSUE THREAD

**Issue by Daryes** [keycloak/keycloak-ui#3386] opened 2022-09-24 13:20 UTC
### Describe the bug

On the admin console, in any realm, select the clients panel to view the list of all clients
Click on one of the client, to view or edit it : the page will load and show : Error: Minified React error #306;
Full error in the browser debug:
```
 Error: Minified React error #306; visit https://reactjs.org/docs/error-decoder.html?invariant=306&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    Ea https://...sensitive:removed.../resources/j6isj/admin/keycloak.v2/assets/index.4ad08902.js:27
    Ma https://...sensitive:removed.../resources/j6isj/admin/keycloak.v2/assets/index.4ad08902.js:27
    o5 https://...sensitive:removed.../resources/j6isj/admin/keycloak.v2/assets/index.4ad08902.js:27
    Tt https://...sensitive:removed.../resources/j6isj/admin/keycloak.v2/assets/index.4ad08902.js:27
    o6 https://...sensitive:removed.../resources/j6isj/admin/keycloak.v2/assets/index.4ad08902.js:25
    z0 https://...sensitive:removed.../resources/j6isj/admin/keycloak.v2/assets/index.4ad08902.js:23
    unstable_runWithPriority https://...sensitive:removed.../resources/j6isj/admin/keycloak.v2/assets/index.4ad08902.js:19
    he https://...sensitive:removed.../resources/j6isj/admin/keycloak.v2/assets/index.4ad08902.js:23
    z0 https://...sensitive:removed.../resources/j6isj/admin/keycloak.v2/assets/index.4ad08902.js:23
    q https://...sensitive:removed.../resources/j6isj/admin/keycloak.v2/assets/index.4ad08902.js:19
    onmessage https://...sensitive:removed.../resources/j6isj/admin/keycloak.v2/assets/index.4ad08902.js:19
```

### Version

19.0.2

### Expected behavior

opening a client and being able to view or edit its configuration

### Actual behavior

The said error, no much information available aside the message

### How to Reproduce?

The error 306 happens on any clients, event the `account` or `account-console` default clients
And also after a new client is created : the creation works, the client cannot be viewed/edited

If the admin them is changed to keycloak (v1), it works correctly with the old UI.

No idea about the real cause, the browser does not return anything more, and keycloak does not complain on the server side.
A possible source could be an extra mapper, activated by default,  linked to a ldap server under User Federation.

### Anything else?

The installation was previously running Keycloak v16.1.1 (docker).  
Then upgraded directly to keycloak v19.0.1, and v19.0.2 after

It is using the docker image from: `quay.io/keycloak/keycloak`
Activated profile is : `prod`  (image default, afaik)
Current command line is : `[ "start", "--auto-build" ]`

No real problem encountered when migrating, and keycloak itself is working correctly with all the clients requesting an authorization.  
Only the UI v2 has this bug, the v1 when changing the theme is OK

Using Firefox ESR v91.10, will try with the new ESR v102.1

**Comment by ssilvert** [comment] 2022-09-28 18:31
@Daryes I don't see this on my end but I don't have an LDAP set up.  Anything you can do to give more specific steps to reproduce will help us find a resolution a lot faster.  Maybe you can verify that it does have something to do with LDAP and the extra mapper you were talking about?

**Comment by ombarek** [comment] 2022-09-29 12:57
Dear, I have the same problem with only a browser message: "Minified React error #306; visit https://reactjs.org/docs/error-decoder.html?invariant=306&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings."
No information in the log sever.
I installed keycloak 19.0.1 on Kubernetes with keycloak operator (olm) and I've connected my LDAP without problem.
My browser is Firefox 105.0.1 on linux.
I tested on Chromium and I can obtain the good UI with no error with keycloak.v2 default theme (version 105.0.5195.125). 
I changed Admin console theme to v1 and I could use Firefox in this case.
Back to keycloak.v2  obtain the same problem with firefox only.

NB: after change v2 to v1, server log show this error. I don't know if it can help you.
12:57:25,544 ERROR [org.keycloak.services.scheduled.ScheduledTaskRunner] (Timer-2) Failed to run scheduled task ClearExpiredClientInitialAccessTokens: java.lang.IllegalAccessError: class org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner$1 tried to access protected field org.keycloak.services.scheduled.ScheduledTaskRunner.task (org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner$1 is in unnamed module of loader 'org.keycloak.keycloak-model-legacy-private@19.0.2' @1fa39bf0; org.keycloak.services.scheduled.ScheduledTaskRunner is in unnamed module of loader 'org.keycloak.keycloak-server-spi-private@19.0.2' @5cea6320)	at org.keycloak.keycloak-model-legacy-private@19.0.2//org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner$1.call(ClusterAwareScheduledTaskRunner.java:56)	at org.keycloak.keycloak-model-legacy-private@19.0.2//org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner$1.call(ClusterAwareScheduledTaskRunner.java:52)	at org.keycloak.keycloak-model-infinispan@19.0.2//org.keycloak.cluster.infinispan.InfinispanClusterProvider.executeIfNotExecuted(InfinispanClusterProvider.java:78) at org.keycloak.keycloak-model-legacy-private@19.0.2//org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner.runTask(ClusterAwareScheduledTaskRunner.java:52) at org.keycloak.keycloak-server-spi-private@19.0.2//org.keycloak.services.scheduled.ScheduledTaskRunner.run(ScheduledTaskRunner.java:54)
	at org.keycloak.keycloak-services@19.0.2//org.keycloak.timer.basic.BasicTimerProvider$1.run(BasicTimerProvider.java:53)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)

Best

**Comment by Daryes** [comment] 2022-09-29 20:19
> @Daryes I don't see this on my end but I don't have an LDAP set up. Anything you can do to give more specific steps to reproduce will help us find a resolution a lot faster. Maybe you can verify that it does have something to do with LDAP and the extra mapper you were talking about?

That's the main problem : the error is only on the browser side, and the error stack is from the browser debug console.
It occurs immediately when trying to access a client details, from the "clients" panel. Even with a new client freshly created.

The only common element with the new client is the extra mapper that automatically propagate to all clients in a client scope : 
* Under User Federation, a provider is created (Active Directory), with an additional mapper named `username (userPrincipalName)` : user model attribute=usernameAlt, ldap attribute=userPrincipalName
* Under Client Scopes : a new scope is created, named `username_alt`, protocol=openid-connect, include in token scope=on, and with 2 mappers
  * one with the user attribute `username` set to the token claim name `login`
  * another with the user attribute `usernameAlt` set to the token claim name `username_alt`

This client scope will appear in all client, old or new, as an default or optional available client scope.

**Comment by ombarek** [comment] 2022-09-30 07:23
Hi,
I don't know if it can help you but I check firefox console to find more information.
I obtain these info
```
Error: Minified React error #306; visit https://reactjs.org/docs/error-decoder.html?invariant=306&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    Ea https://MYKEYCLOAKURL/auth/resources/wb7k1/admin/keycloak.v2/assets/index.4ad08902.js:27
    Ma https://MYKEYCLOAKURL/auth/resources/wb7k1/admin/keycloak.v2/assets/index.4ad08902.js:27
    o5 https://MYKEYCLOAKURL/auth/resources/wb7k1/admin/keycloak.v2/assets/index.4ad08902.js:27
    Tt https://MYKEYCLOAKURL/auth/resources/wb7k1/admin/keycloak.v2/assets/index.4ad08902.js:27
    o6 https://MYKEYCLOAKURL/auth/resources/wb7k1/admin/keycloak.v2/assets/index.4ad08902.js:25
    z0 https://MYKEYCLOAKURL/auth/resources/wb7k1/admin/keycloak.v2/assets/index.4ad08902.js:23
    unstable_runWithPriority https://MYKEYCLOAKURL/auth/resources/wb7k1/admin/keycloak.v2/assets/index.4ad08902.js:19
    he https://MYKEYCLOAKURL/auth/resources/wb7k1/admin/keycloak.v2/assets/index.4ad08902.js:23
    z0 https://MYKEYCLOAKURL/auth/resources/wb7k1/admin/keycloak.v2/assets/index.4ad08902.js:23
    q https://MYKEYCLOAKURL/auth/resources/wb7k1/admin/keycloak.v2/assets/index.4ad08902.js:19
    onmessage https://MYKEYCLOAKURL/auth/resources/wb7k1/admin/keycloak.v2/assets/index.4ad08902.js:19
    js https://MYKEYCLOAKURL/auth/resources/wb7k1/admin/keycloak.v2/assets/index.4ad08902.js:19
    __commonJS https://MYKEYCLOAKURL/auth/resources/wb7k1/admin/keycloak.v2/assets/index.4ad08902.js:1
    js https://MYKEYCLOAKURL/auth/resources/wb7k1/admin/keycloak.v2/assets/index.4ad08902.js:19
    __commonJS https://MYKEYCLOAKURL/auth/resources/wb7k1/admin/keycloak.v2/assets/index.4ad08902.js:1
    js https://MYKEYCLOAKURL/auth/resources/wb7k1/admin/keycloak.v2/assets/index.4ad08902.js:19
    __commonJS https://MYKEYCLOAKURL/auth/resources/wb7k1/admin/keycloak.v2/assets/index.4ad08902.js:1
    js https://MYKEYCLOAKURL/auth/resources/wb7k1/admin/keycloak.v2/assets/index.4ad08902.js:27
    __commonJS https://MYKEYCLOAKURL/auth/resources/wb7k1/admin/keycloak.v2/assets/index.4ad08902.js:1
    <anonymous> https://MYKEYCLOAKURL/auth/resources/wb7k1/admin/keycloak.v2/assets/index.4ad08902.js:81
index.4ad08902.js:25:73
    q3 https://MYKEYCLOAKURL/auth/resources/wb7k1/admin/keycloak.v2/assets/index.4ad08902.js:25
    payload https://MYKEYCLOAKURL/auth/resources/wb7k1/admin/keycloak.v2/assets/index.4ad08902.js:25
    vt https://MYKEYCLOAKURL/auth/resources/wb7k1/admin/keycloak.v2/assets/index.4ad08902.js:23
    aa https://MYKEYCLOAKURL/auth/resources/wb7k1/admin/keycloak.v2/assets/index.4ad08902.js:23
    Ea https://MYKEYCLOAKURL/auth/resources/wb7k1/admin/keycloak.v2/assets/index.4ad08902.js:27
    Ma https://MYKEYCLOAKURL/auth/resources/wb7k1/admin/keycloak.v2/assets/index.4ad08902.js:27
    o5 https://MYKEYCLOAKURL/auth/resources/wb7k1/admin/keycloak.v2/assets/index.4ad08902.js:27
    Tt https://MYKEYCLOAKURL/auth/resources/wb7k1/admin/keycloak.v2/assets/index.4ad08902.js:27
    o6 https://MYKEYCLOAKURL/auth/resources/wb7k1/admin/keycloak.v2/assets/index.4ad08902.js:25
    z0 https://MYKEYCLOAKURL/auth/resources/wb7k1/admin/keycloak.v2/assets/index.4ad08902.js:23
    unstable_runWithPriority https://MYKEYCLOAKURL/auth/resources/wb7k1/admin/keycloak.v2/assets/index.4ad08902.js:19
    he https://MYKEYCLOAKURL/auth/resources/wb7k1/admin/keycloak.v2/assets/index.4ad08902.js:23
    z0 https://MYKEYCLOAKURL/auth/resources/wb7k1/admin/keycloak.v2/assets/index.4ad08902.js:23
    q https://MYKEYCLOAKURL/auth/resources/wb7k1/admin/keycloak.v2/assets/index.4ad08902.js:19
    onmessage https://MYKEYCLOAKURL/auth/resources/wb7k1/admin/keycloak.v2/assets/index.4ad08902.js:19
    (Asynchrone : EventHandlerNonNull)
    js https://MYKEYCLOAKURL/auth/resources/wb7k1/admin/keycloak.v2/assets/index.4ad08902.js:19
    __commonJS https://MYKEYCLOAKURL/auth/resources/wb7k1/admin/keycloak.v2/assets/index.4ad08902.js:1
    js https://MYKEYCLOAKURL/auth/resources/wb7k1/admin/keycloak.v2/assets/index.4ad08902.js:19
    __commonJS https://MYKEYCLOAKURL/auth/resources/wb7k1/admin/keycloak.v2/assets/index.4ad08902.js:1
    js https://MYKEYCLOAKURL/auth/resources/wb7k1/admin/keycloak.v2/assets/index.4ad08902.js:19
    __commonJS https://MYKEYCLOAKURL/auth/resources/wb7k1/admin/keycloak.v2/assets/index.4ad08902.js:1
    js https://MYKEYCLOAKURL/auth/resources/wb7k1/admin/keycloak.v2/assets/index.4ad08902.js:27
    __commonJS https://MYKEYCLOAKURL/auth/resources/wb7k1/admin/keycloak.v2/assets/index.4ad08902.js:1
    <anonyme> https://MYKEYCLOAKURL/auth/resources/wb7k1/admin/keycloak.v2/assets/index.4ad08902.js:81
```
And in another way, (sorry some lines are in french)
```
b is null mozjexl.js:1
    Identifier resource://gre/modules/components-utils/mozjexl.js:1
[Exception... "Component returned failure code: 0x80004001 (NS_ERROR_NOT_IMPLEMENTED) [nsIAppStartup.secondsSinceLastOSRestart]"  nsresult: "0x80004001 (NS_ERROR_NOT_IMPLEMENTED)"  location: "JS frame :: resource:///modules/BrowserGlue.jsm :: _collectStartupConditionsTelemetry :: line 1590"  data: no] BrowserGlue.jsm:1590:9
    _collectStartupConditionsTelemetry resource:///modules/BrowserGlue.jsm:1590
    BG__onFirstWindowLoaded resource:///modules/BrowserGlue.jsm:1698
    BG_observe resource:///modules/BrowserGlue.jsm:938
    _delayedStartup chrome://browser/content/browser.js:2140
    _delayedStartup self-hosted:1356
Cette page est en mode de compatibilité (quirks). La mise en page peut en être affectée. Pour le mode standard, utilisez « <!DOCTYPE html> ».
hiddenWindow.html
L’évènement « key » n’est pas disponible pour certaines dispositions de clavier : key="r" modifiers="accel,alt" id="key_toggleReaderMode" browser.xhtml
L’évènement « key » n’est pas disponible pour certaines dispositions de clavier : key="x" modifiers="accel,alt" id="" browser.xhtml
L’évènement « key » n’est pas disponible pour certaines dispositions de clavier : key="q" modifiers="accel,alt" id="" browser.xhtml
L’évènement « key » n’est pas disponible pour certaines dispositions de clavier : key="s" modifiers="accel,alt" id="" browser.xhtml
L’évènement « key » n’est pas disponible pour certaines dispositions de clavier : key="t" modifiers="accel,alt" id="" browser.xhtml
L’évènement « key » n’est pas disponible pour certaines dispositions de clavier : key="i" modifiers="accel,alt,shift" id="key_browserToolbox" browser.xhtml
AbortError: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved 2 ConduitsParent.jsm:362
    _raceResponses resource://gre/modules/ConduitsParent.jsm:362
Element.releaseCapture() est obsolète. Utilisez Element.releasePointerCapture() à la place. Pour plus d’informations https://developer.mozilla.org/fr/docs/Web/API/Element/releasePointerCapture menupopup.js:166:13
AbortError: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved 2 ConduitsParent.jsm:362
    _raceResponses resource://gre/modules/ConduitsParent.jsm:362
b is null mozjexl.js:1
    Identifier resource://gre/modules/components-utils/mozjexl.js:1
New rollout bug-1791587-rollout-revert-unplanned-config-change-release-105-105 does not change any preferences. PreferenceRolloutAction.jsm:144
    _run resource://normandy/actions/PreferenceRolloutAction.jsm:144
    InterpretGeneratorResume self-hosted:1819
    AsyncFunctionNext self-hosted:807
Propriété « -moz-border-radius » inconnue.  Déclaration abandonnée. codemirror.css:244:22
Éléments correspondant au sélecteur : .CodeMirror pre.CodeMirror-line, .CodeMirror pre.CodeMirror-line-like
NodeList []
​length: 0
​<prototype>: NodeListPrototype { item: item(), keys: keys(), values: values(), … }
​​constructor: function ()
​​​isInstance: function isInstance()
​​​length: 0
​​​name: "NodeList"
​​​prototype: NodeListPrototype { item: item(), keys: keys(), values: values(), … }
​​​Symbol(Symbol.hasInstance): function Symbol.hasInstance()
​​​<prototype>: function ()
​​entries: function entries()
​​forEach: function forEach()
​​item: function item()
​​keys: function keys()
​​length: 
​​values: function values()
​​Symbol(Symbol.iterator): function values()
​​Symbol(Symbol.toStringTag): "NodeList"
​​<get length()>: function length()
​​<prototype>: Object { … }
```
Sorry, I lost some increment in my copy-paste.
Best.

**Comment by superspeed500** [comment] 2022-10-05 17:01
Might not be related, but I encountered a simular issue with the same error message on my Keycloack 19.0.2 installation running on Fedora server 36 inside a docker (moby-engine-20.10.18-1.fc36.x86_64) container. My instance also have a LDAP-connection to an AD-domain (Samba domain controllers). The interesting thing in my scenario was that I had no issues when accessing from my Windows 10 computer using firefox 105.0.1. Same with Firefox 102.3.0esr on Debian 11. The only system with the issue was Firefox 105.0.1 on macOs 12.6.

What i tried on the affected system was deleting everything from "Local storage" and "Cookies" for my keycloack domain in the developer console. That seems to have temporary fixed the issue for me at least.

The interesting thing is that the error returns if I change tenant. I have to delete "Local storage" and "Cookies" even when switching to the same tenant as currently selected from the dropdown.

**Comment by ajcollins** [comment] 2022-10-13 21:31
I experienced the same issue with a newly installed 19.0.3 (macOS 12.6, Safari 16.0). This was running in docker using the same default image with no external connections setup.

Opening the browser's developer console and disabling the cache solved the issue. Once resolved, the cache was re-enabled and it continues to work.

**Comment by Daryes** [comment] 2022-11-11 11:23
As a head-up, I've finally updated to Firefox 102.3 ESR, and tested the admin.v2 UI. 
It worked immediately, until a change was made to a client.
As per [ajcollins](https://github.com/ajcollins) report, disabling the browser cache took care of the issue. So while it is a working fix, it is meant to be temporary.

This said, if the cache is active, it seems to me the admin.v2 UI : 
* expects in the cache some extra objects that weren't loaded yet, like any provider or client scope
* is not able to always force a refresh when a change occurred on a client using such extra object

**Comment by jonkoops** [comment] 2023-01-24 13:33
We have landed some fixes in this regard, could someone verify this is still an issue under the [latest nightly](https://github.com/keycloak/keycloak/releases/tag/nightly)?

**Comment by superspeed500** [comment] 2023-02-15 19:08
Sorry late reply. I started up the nightly build on my Mac using `bin/kc.sh start-dev` as noted in the README file. 

I then did the following:

1. Created a new admin user.
2. Logged into the admin panel with the new user.
3. Went to the client tab and created two new clients.
4. Createed a new realm and switched to it.
5. Created a new client in the other realm.
6. Switched back to the client tab in the master realm.

I experienced no issues, but be adviced that this test is not a replica of my home production environment. And it would be nice if someone else can confirm as well :)

**Comment by jonkoops** [comment] 2023-02-16 09:32
Is there a list to be found somewhere of all the actively supported ESR versions of Firefox? Or do they only support the last one at any given time?

**Comment by superspeed500** [comment] 2023-02-17 17:55
Looks like ESR support is for the current release and the past release in an interim phase (12 weeks). At least thats how I understand this document: https://support.mozilla.org/en-US/kb/firefox-esr-release-cycle

**Comment by Daryes** [comment] 2023-02-21 21:55
To complete superspeed500 explanation, basically you'll have the current ESR major version to support, but also the previous major one : it is common in company to delay for a while before upgrading to the current version. 
If required, you can found the previous ESR versions in portable packages on portableapps.com, under "legacy".

This aside, I didn't see a docker version for the nightly (or I was blind while searching). Instead, I've upgraded to the latest keycloak v20.0.5, and it seems the problem was fixed.

I reactivated the browser cache, and navigated through the multiple panels in the admin.v2 UI, I didn't encounter any error.
Even the refresh problem didn't occur (the UI was still presenting old values after a change on an object, that could be fixed by reloading the page with F5)

Looks good for me.

**Comment by ssilvert** [comment] 2023-02-21 22:12
Thanks to @Daryes and @superspeed500 for confirming the fix in the latest code.  I'm going to close this now but we can always reopen if anyone has problems.

**Closed by ssilvert** 2023-02-21 22:12 UTC
Labels: kind/bug, impact/high, area/section/clients, area/admin/ui
