### ISSUE TITLE
can't convert undefined to object (Default Identity Provider)

### ISSUE THREAD

**Issue by bovy89** [keycloak/keycloak-ui#3513] opened 2022-10-07 12:06 UTC
### Describe the bug

Is impossible to configure an identity provider as "default identity provider" (https://www.keycloak.org/docs/latest/server_admin/#default_identity_provider)

### Version

19.0.3

### Expected behavior

Open configuration window

### Actual behavior

![image](https://user-images.githubusercontent.com/697408/194548798-425cdbea-b66d-4cd3-ab9d-0ab89221d9ac.png)

### How to Reproduce?

1) Creare a new realm (not master)
2) Configure an identity provider
3) Click Authentication in the menu.
4) Click the Browser flow.
5) Click the gear icon on the Identity Provider Redirector row ---> error

**Comment by ssilvert** [comment] 2022-10-07 13:53
I could not reproduce this.  I think it is already fixed though.  Can you check the latest nightly build and let us know?

https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by bovy89** [comment] 2022-10-07 14:38
19.0.3 ---> error
nightly --> seems ok (configuration window displayed) but after you set the default identity provider the same window display nothing

![image](https://user-images.githubusercontent.com/697408/194579231-9b8cab45-ac34-4506-ab5e-f49908541f9b.png)

I thought it was fixed in 19.0.3 reading this: https://github.com/keycloak/keycloak-ui/issues/3375

**Comment by jonkoops** [comment] 2022-10-08 17:00
This has not been backported to 19.0.3. Most fixes will come with the Keycloak 20 release, which will be coming soon.

**Comment by jonkoops** [comment] 2022-10-08 17:01
> but after you set the default identity provider the same window display nothing

@bovy89 if you feel this is a bug, could you report it as a separate issue? Closing this one as the problem has been resolved on `main`.

**Closed by jonkoops** 2022-10-08 17:01 UTC
Labels: kind/bug, status/triage
