### ISSUE TITLE
 Message customization - plurals not working for other than English

### ISSUE THREAD

**Issue by michbudz** [keycloak/keycloak-ui#3817] opened 2022-11-22 08:55 UTC
### Describe the bug

Hi,
I have a problem with message customization in Polish.
I created my own theme with below files:

```
themes/mytheme/admin/messages/admin-messages_pl.properties
themes/mytheme/admin/theme.properties
```

theme.properties contains:
```
parent=keycloak
locales=pl
```

Everything works perfect for keycloak theme, but when I change
```
parent=keycloak
```
to
```
parent=keycloak.v2
```

I can’t see my custom Polish messages, instead I see the default English ones.

Do you know why cannot customize administration console messages in keycloak.v2 theme?

### Version

20.0.1

### Expected behavior

Use of mine custom messages from admin-messages_pl.properties

### Actual behavior

Keycloak uses the default en messages

### How to Reproduce?

Use Keycloak 20.0.1 from docker.

**Comment by ssilvert** [comment] 2022-11-28 20:07
For `keycloak.v2` you will override different files.  It uses JSON files, which will be located in `keycloak.v2/admin/resources/resources/pl`.  

Source is [here](https://github.com/keycloak/keycloak-ui/tree/main/apps/admin-ui/public/resources/pl).  As you can see, all the files for Polish are empty.  We would be happy to accept contributions.

Also, please let me know if this is working so I can close this issue.  I haven't actually tried to do this myself.

**Comment by michbudz** [comment] 2022-11-30 08:58
Thanks @ssilvert, it works.
I noticed one issue, if I overwrite plural messages it doesn't work, the EN value is always taken.
For example `"deleteConfirmDialog_other": "Polish plural message"` in file `users.json` doesn't work, but
`"deleteConfirmDialog_one": "Polish singular message"` works great.

I will try to contribute translations.

**Comment by ssilvert** [comment] 2022-11-30 20:09
OK.  I'll leave this open and we will look into the plural issue.  Thanks for the feedback.

**Comment by edewit** [comment] 2022-12-16 07:14
@michbudz are you sure that it doesn't work? I can't reproduce it

**Comment by edewit** [comment] 2023-03-02 11:20
closing can't reproduce, feel free to re-open

**Closed by edewit** 2023-03-02 11:20 UTC
Labels: kind/bug, impact/medium, area/section/other, area/admin/ui
