### ISSUE TITLE
KC19.0.3: Captcha: Error while getting access to its settings

### ISSUE THREAD

**Issue by semangard** [keycloak/keycloak-ui#3476] opened 2022-10-04 13:24 UTC
### Describe the bug

Hello,

I have the error below at the step 8 while editing the built-in 'registration' flow: 
![image](https://user-images.githubusercontent.com/57065741/193829860-4c14ef6c-df88-4779-b887-37ca047786af.png)

![image](https://user-images.githubusercontent.com/57065741/193829920-5a7169bf-d126-46a2-b9bc-c06e078ffc06.png)

### Version

19.0.2

### Expected behavior

Be able to define reCAPTCHA settings on KC v19.x

### Actual behavior

Got the error:

![image](https://user-images.githubusercontent.com/57065741/193829920-5a7169bf-d126-46a2-b9bc-c06e078ffc06.png)

### How to Reproduce?

Execute the process indicated by KC doc till step 8 for the built-in 'registration' flow: 

![image](https://user-images.githubusercontent.com/57065741/193829860-4c14ef6c-df88-4779-b887-37ca047786af.png)

**Comment by semangard** [comment] 2022-10-04 15:37
Additional info : I have the same issue with any other gear icon into flows (for ex with user session count limiter).

**Comment by ssilvert** [comment] 2022-10-05 17:50
I could not reproduce this.  It may already be fixed. Can you try it out with the latest nightly build and let us know?

https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by semangard** [comment] 2022-10-07 09:13
@ssilvert : I recreated form scratch a docker with the nightly release and I do not have anymore the bug

**Comment by ssilvert** [comment] 2022-10-08 21:25
@semangard Thanks for getting back to us about the nightly build.  For 19.0.3, we only cherry picked a few critical bug fixes.  The rest will be in 20.0.0.

I'm going to close this since it should be fixed now.

**Closed by ssilvert** 2022-10-08 21:25 UTC
Labels: kind/bug, status/triage
