### ISSUE TITLE
Condition with property of type MULTIVALUED_STRING_TYPE is not displayed/editable after upgrade to latest version

### ISSUE THREAD

**Issue by raphisuter** [keycloak/keycloak-ui#4273] opened 2023-01-26 11:17 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

We developed a condition which allows us to configure multiple networks which are excluded from login with OTP and only use username password form. While testing after upgrading from V15 to V20 of Keycloak we found this issue. The existing values cannot be displayed in Keycloak V20 and cannot be edited or saved.

V15:
![image](https://user-images.githubusercontent.com/7498360/214817793-68c18de4-a1f7-4f14-a8c3-64f2fc9dde9c.png)

V20:
![image](https://user-images.githubusercontent.com/7498360/214818003-efd6a638-4693-4005-916b-765d9d62cad6.png)

In Chrome DevTools it is visible that the data is present and transmitted to the UI:
![image](https://user-images.githubusercontent.com/7498360/214818778-9f336a82-a629-4532-8140-c0937e7631f3.png)

If I click clear and try to reset it again, there is an Exception thrown in the console.
![image](https://user-images.githubusercontent.com/7498360/214819484-2197e57e-2235-4c15-89a5-fc5519bf5c4d.png)

### Version

20.0.3

### Expected behavior

Property should be displayed, editable and savable as in previous versions.

### Actual behavior

Existing values are not displayed. Reseting it leads to an exception.

### How to Reproduce?

1. Create Condition with Property of type MULTIVALUED_STRING_TYPE
2. Create new Authenticaton Flow
3. Add Condition to Authentication Flow
4. Set Value of MULTIVALUED_STRING_TYPE Property
5. Save

**Comment by ssilvert** [comment] 2023-01-27 12:16
Thanks for the update @raphisuter.  Transferring to the keycloak-ui repo.

**Comment by edewit** [comment] 2023-01-30 11:22
can't reproduce this, but made a component test

**Comment by raphisuter** [comment] 2023-01-30 12:38
@edewit okay that was unexpected. Any idea how we are going to progress further? This error/bug holds us up on upgrading from V15 to V20.

**Comment by ssilvert** [comment] 2023-01-30 12:45
@raphisuter Is there something you can send us that reproduces the problem?

**Comment by raphisuter** [comment] 2023-01-30 15:42
I'm going to try and give you as much information as you need to reproduce. I guess it will be more of a guess what helps rather than perfect helping information. If you have an idea what I should focus on let me know (@ssilvert @edewit)

General information:
- JDK16
- Oracle Database 19c
- Started on windows OpenJDK (bare metal)
- Values in DB have it's origin from keycloak v.13
- ConditionalAuthenticator 
- Keycloak used for testing: V20.0.2, V20.0.3, nightlybuild (27.01.2023)

I tried to dig deeper and found out the error from the DevTools is coming from an asset in the keycloak.v2 theme.
![image](https://user-images.githubusercontent.com/7498360/215517190-328414ea-9868-4be1-a929-dd14e83c4028.png)

I also inspected the values which are sent from keycloak to keycloak-ui and back and there I can see the data is not structured the same way as when I receive them.
Receive in UI:
![image](https://user-images.githubusercontent.com/7498360/215518908-4da57836-fa7c-41a4-ace6-64fea421ed12.png)
Send back from UI:
![image](https://user-images.githubusercontent.com/7498360/215519008-502f0907-5a86-4120-82be-47c8fad6d9e6.png)

The data is not a single string anymore (separated by double hashtag ##), now it's a String Array. Seeing this the error MismatchedInputException makes total sense. Seeing the datatable structure of `authenticator_config_entry`, there must be some kind of parsing, will this be done insied keycloak or keycloak-ui?

Code Snippets:
ConditionalAuthenticatorFactory
![image](https://user-images.githubusercontent.com/7498360/215522257-09182acc-8ab6-4e0c-8bea-6cfdc0098878.png)

**Comment by raphisuter** [comment] 2023-02-02 11:19
Hi @ssilvert @edewit

I invested some time and checked out the master branch of keycloak-ui and build the admin-ui app and configured it to receive the data from my local windows keycloak mentioned in my post above. Had to import the security-admin-console-v2 to log in with the UI but I made it to work. The error also exists there in combination with our ConditionalAuthenticator. So i started digging deeper and startet debugging while also checking out the PR https://github.com/keycloak/keycloak-ui/pull/4287 to get some information.

It took me a lot of time, but I found the source of the problem and fixed it. I don't know if that is the appropriate way because I'm no expert in keycloak-ui, but I guess this is the decision of the reviewer. My PR -> https://github.com/keycloak/keycloak-ui/pull/4306

Kind regards

**Closed** 2023-02-03 11:26 UTC
Labels: kind/bug, impact/high, area/section/authentication, area/admin/ui

**Comment by jonkoops** [comment] 2023-02-03 11:54
Patch for this issue does not apply cleanly so this will have to come along in the next major.

**Comment by raphisuter** [comment] 2023-02-03 12:29
ok that's a pity. We'll have to wait for the next major release for our upgrade.

**Comment by jonkoops** [comment] 2023-02-06 11:30
@raphisuter as a workaround you could keep using the older theme for the Admin Console until the next version.

**Comment by raphisuter** [comment] 2023-02-09 07:54
@jonkoops True. Even though we are going to wait for the next release to reduce the amount of testing needed to introduce it to our dev environment. I know there is no estimate when the next release will take place, but are there any sources where I can get Information about the next major release expect from the official website?

I guess the label 21.0.0 need to be applied to this issue?

**Comment by jonkoops** [comment] 2023-02-11 19:23
I expect we'll be releasing Keycloak 21 somewhere at the end of February possibly the start of March (but no guarantees).

**Comment by raphisuter** [comment] 2023-03-02 09:21
@jonkoops was this released with V21? I'm asking because it is not tagged to the milestone.

**Comment by edewit** [comment] 2023-03-02 10:08
yes a new release takes everything from main, point releases cherry pick issues
