### ISSUE TITLE
Error! Failed to send email, and Error 400 API

### ISSUE THREAD

**Issue by AzagraMac** [keycloak/keycloak-ui#4423] opened 2022-11-16 16:44 UTC
### Area

account/ui

### Describe the bug

Configured the mail in **admin/master/console/#/master/realm-settings/email**, a Gmail account, save the credentials and then click Test Connection, sometimes it gives ok, and other times failed, you save again and it gives ok, until you refresh the page and it gives error again. 

By API also gives a 400 error when making a POST request. 

![image](https://user-images.githubusercontent.com/571796/202239816-78746090-214c-4017-8e75-9625281c7e37.png)
![image](https://user-images.githubusercontent.com/571796/202240029-de19fe57-59f3-4043-82bb-e8ee00fed945.png)

![image](https://user-images.githubusercontent.com/571796/202239736-ef1ac897-3eb0-46b6-b241-66fe57a87fad.png)

### Version

19.0.2

### Expected behavior

Save the email credentials, perform a test run and make sure it does not fail. 

### Actual behavior

save the credentials and then click Test Connection, sometimes it gives ok, and other times failed, you save again and it gives ok, until you refresh the page and it gives error again. 

By API also gives a 400 error when making a POST request. 

### How to Reproduce?

Configured the mail in **admin/master/console/#/master/realm-settings/email**, a Gmail account, save the credentials and then click Test Connection, sometimes it gives ok, and other times failed, you save again and it gives ok, until you refresh the page and it gives error again. 
![image](https://user-images.githubusercontent.com/571796/202239736-ef1ac897-3eb0-46b6-b241-66fe57a87fad.png)

### Anything else?
```
2022-11-16 16:43:28,159 ERROR [org.keycloak.services] (executor-thread-1082) KC-SERVICES0029: Failed to send email: javax.mail.AuthenticationFailedException: failed to connect, no password specified?
        at javax.mail.Service.connect(Service.java:376)
        at javax.mail.Service.connect(Service.java:222)
```
_No response_

**Comment by ssilvert** [comment] 2023-02-17 19:36
This one got mislabeled, which led to not being handled in a timely manner.  Moving to keycloak-ui repo.

**Comment by edewit** [comment] 2023-02-20 14:26
can't reproduce this, this is what I did:

1. go to master realm
2. set email host, port, username and password
3. create new realm test
4. go to email set host, port, username and password
5. hit verify to see it work
6. back to master realm email hit verify and it works

if these are not the right steps what are?

**Comment by edewit** [comment] 2023-03-02 07:06
Closing this issue as I can't reproduce and haven't heard back from the author, if this remains an issue feel free to re-open this

**Closed by edewit** 2023-03-02 07:06 UTC
Labels: kind/bug, impact/high, area/admin/ui, team/ui
