### ISSUE TITLE
Can't configure authenticators with MULTIVALUED_STRING_TYPE fields

### ISSUE THREAD

**Issue by kherock** [keycloak/keycloak-ui#3914] opened 2022-12-01 14:13 UTC
### Describe the bug

When saving an authenticator config that uses `ProviderConfigProperty.MULTIVALUED_STRING_TYPE` I get the following exception (status 500) 

```
ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-3) Uncaught server error: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.lang.String` from Array value (token `JsonToken.START_ARRAY`)
```

### Version

20.0.1

### Environment

Chrome/Edge 107

### Expected behavior

String array should be serialized joining `##` in the request body

### Actual behavior

Config field is sent as an array

### How to Reproduce?

Keycloak doesn't have any built-in authenticators that use this config type, so I can't describe any steps for setting this up out of the box. An authenticator factory with a implementation like the following needs to be configured on the new UI

```java
import org.keycloak.Config;
import org.keycloak.authentication.Authenticator;
import org.keycloak.authentication.AuthenticatorFactory;
import org.keycloak.models.AuthenticationExecutionModel;
import org.keycloak.models.KeycloakSession;
import org.keycloak.models.KeycloakSessionFactory;
import org.keycloak.provider.ProviderConfigProperty;

import java.util.ArrayList;
import java.util.List;

public class SessionRestrictionAuthenticatorFactory implements AuthenticatorFactory {
    public static final String PROVIDER_ID = "custom-multivalued-authenticator";
  
    private static final List<ProviderConfigProperty> configProperties = new ArrayList<ProviderConfigProperty>();
    static {
        ProviderConfigProperty myProperty = new ProviderConfigProperty();
        myProperty.setName("clients");
        myProperty.setLabel("Client Name");
        myProperty.setHelpText(
                "Client ID");
                myProperty.setType(ProviderConfigProperty.MULTIVALUED_STRING_TYPE);
        configProperties.add(myProperty);
    }

    private static AuthenticationExecutionModel.Requirement[] REQUIREMENT_CHOICES = {
            AuthenticationExecutionModel.Requirement.REQUIRED,
            AuthenticationExecutionModel.Requirement.DISABLED
    };

    @Override
    public String getDisplayType() {
        return "Custom authenticator";
    }

    @Override
    public String getReferenceCategory() {
        return null;
    }

    @Override
    public boolean isConfigurable() {
        return true;
    }

    @Override
    public AuthenticationExecutionModel.Requirement[] getRequirementChoices() {
        return REQUIREMENT_CHOICES;
    }

    @Override
    public boolean isUserSetupAllowed() {
        return false;
    }

    @Override
    public String getHelpText() {
        return "test";
    }

    @Override
    public List<ProviderConfigProperty> getConfigProperties() {
       return configProperties;
    }

    @Override
    public Authenticator create(KeycloakSession keycloakSession) {
        return null; // replace with impl
    }

    @Override
    public void init(Config.Scope scope) {

    }

    @Override
    public void postInit(KeycloakSessionFactory keycloakSessionFactory) {

    }

    @Override
    public void close() {

    }

    @Override
    public String getId() {
        return PROVIDER_ID;
    }
}
```

**Comment by ssilvert** [comment] 2022-12-01 18:31
Thanks for reporting this @kherock.  I believe this issue is a duplicate of https://github.com/keycloak/keycloak-ui/issues/3559.  I'm going to close this issue and bump the priority of the one that is already open.

**Closed by ssilvert** 2022-12-01 18:31 UTC
Labels: kind/bug, status/triage
