### ISSUE TITLE
not able to set up Identity Provider Redirector

### ISSUE THREAD

**Issue by life-tushar1** [keycloak/keycloak-ui#3592] opened 2022-10-17 16:20 UTC
### Describe the bug

for keycloak 19.0.2 i am not able to set Identity Provider Redirector for browser(authentication->browser).

On click of gear icon, I am getting " Cannot convert undefined or null to object"
<img width="1512" alt="Screenshot 2022-10-17 at 9 47 16 PM" src="https://user-images.githubusercontent.com/17873663/196229749-d6312001-f65a-4cde-9df0-1446ea6c40f9.png">

### Version

19.0.2

### Expected behavior

should be able to set the IDP to redirect.

### How to Reproduce?

(authentication->browser).
go to authentication -> browser -> click on gear icon of Identity Provider Redirector

**Comment by ssilvert** [comment] 2022-10-18 00:15
@life-tushar1 This should be fixed in the latest nightly build.  I believe it's a duplicate of https://github.com/keycloak/keycloak-ui/issues/3531.

Can you give the nightly a try and let us know?
https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by life-tushar1** [comment] 2022-10-18 04:32
Hi Stan,

I am looking for a stable build as I am planning to take it to the
production instance.

Thanks and Regards.

**Comment by ssilvert** [comment] 2022-10-18 11:35
@life-tushar1 That's OK.  If you are unable to test the nightly build, we can wait until the next regular release which should be next week with 20.0.0.

I'm going to close this now, but we can reopen if you are still having problems.

**Comment by life-tushar1** [comment] 2022-10-18 15:36
Thank you Stan for the information.

**Closed** 2022-10-19 00:20 UTC
Labels: kind/bug, status/triage
