### ISSUE TITLE
Group management paging bug

### ISSUE THREAD

**Issue by yaoguoh** [keycloak/keycloak-ui#3517] opened 2022-10-08 02:15 UTC
### Describe the bug

1. Pagling button click is invalid
2. Pagling logic error
3. The user gourp configuration also has a problem with paging logic errors

### Version

19.0.3

### Expected behavior

Correct paging

### Actual behavior

![image](https://user-images.githubusercontent.com/18107429/194682962-623a1495-770b-4138-9b20-e69daa467dba.png)
![image](https://user-images.githubusercontent.com/18107429/194682994-85fb15de-1b0f-4bc3-93db-922f5dc86f15.png)

**Comment by ssilvert** [comment] 2022-10-08 21:23
@yaoguoh You will need to be a little more specific.  I don't understand what your issue is.

Also, we are making some major changes to the groups page that should be ready for Keycloak 20.0.0.

**Comment by yaoguoh** [comment] 2022-10-09 01:41
The content of the two display methods is different. 
'admin-ui-groups' what is the query? I haven't found the relevant documentation.

**Comment by lievenjacquot** [comment] 2022-10-11 15:21
I have same issue here,

the /admin/..../admin-ui-groups route not returning the same info that /admin/.../groups?briefRepresentation=false 

In the first case I have only few of my groups displayed. 
In the second case I have all my groups displayed.

I have not found any documentation about admin-ui-groups to know if there is a specific filter.

PS: in the /admin-groups-ui only the first in alphabetical order are displayed, it seems it's not a filter issue

**Comment by ssilvert** [comment] 2022-10-12 14:00
@yaoguoh @lievenjacquot Can you guys look at the latest nightly build and then let me know specific steps to reproduce your problems, if any?  The groups section has had quite a bit of work since the 19.x releases.

https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by yaoguoh** [comment] 2022-10-13 02:14
Docker image ’quay.io/keycloak/keycloak:19.0.3-legacy‘ deployed.
Nightly changes a little big,  It is not very convenient to use without ‘/auth’ routing.

**Comment by yaoguoh** [comment] 2022-10-13 02:22
![image](https://user-images.githubusercontent.com/18107429/195483928-990c1f96-8f5a-4047-9f98-8f9b121cc919.png)
Join groups page has the same problem.

**Comment by sirishkumar** [comment] 2022-10-19 11:33
> I have the same issue here,
> 
> the /admin/..../admin-ui-groups route not returning the same info that /admin/.../groups?briefRepresentation=false
> 
> In the first case I have only few of my groups displayed. In the second case I have all my groups displayed.
> 
> I have not found any documentation about admin-ui-groups to know if there is a specific filter.
> 
> PS: in the /admin-groups-ui only the first in alphabetical order are displayed, it seems it's not a filter issue

I checked the nightly builds, I observed the same behaviour described by @lievenjacquot . As @lievenjacquot said there is no documentation which explains the difference between the groups displayed by the two tabs  

- first  option with table icon invokes the endpoint  admin-ui-groups
-  econd icon with tree view invokes endpoint groups?briefRepresentation=false

**Comment by edewit** [comment] 2022-10-27 07:05
The `admin-ui-groups` only adds fine grained authentication to the group representation

**Comment by edewit** [comment] 2022-10-27 07:07
@sirishkumar From you screenshot I don't see the problem, it is showing page 1 with 2 items?

**Comment by ssilvert** [comment] 2022-11-01 12:39
This should be fixed in Keycloak 20.  I'm going to close this now and if there is still a problem in Keycloak 20 we can reopen.

**Closed by ssilvert** 2022-11-01 12:39 UTC
Labels: kind/bug, impact/high, area/section/groups
