### ISSUE TITLE
UI crash when lots of subgroups

### ISSUE THREAD

**Issue by christopheblin** [keycloak/keycloak-ui#2958] opened 2022-07-12 12:05 UTC
### Describe the bug

After some back-and-forth on a given group, a Network error appears

This error also appears on other screens of the console but it seems that having a big pagination triggers the problem quite "easily"

### Version

18

### Expected behavior

No network errors should occur

### Actual behavior

Crash more or less after 3 to 10 tries

### How to Reproduce?

Here is a video to demonstrate

https://user-images.githubusercontent.com/11044877/178485719-acf2aec5-7e4f-467f-9c97-90fc397d06ec.mov

### Anything else?

I suspect this is somehow caused by the high number of simultaneous requests, but I may be wrong

**Comment by ssilvert** [comment] 2022-08-01 18:46
Hi @christopheblin.  Sorry, we are bit behind on new issues.  We will get to this soon.

**Comment by edewit** [comment] 2022-08-03 11:17
The problem is not the sub groups tab itself but the roles, this is a know issue that will need some server side changes to be fixed. I've created a PR that will fix the group tab by not rendering the sub tabs only on entering them.

**Comment by edewit** [comment] 2022-08-19 12:14
new PR #3095 will also fix the loading of the roles

**Comment by jonkoops** [comment] 2022-08-22 16:07
@edewit since that PR has been merged, can this issue be closed?

**Comment by edewit** [comment] 2022-08-23 08:42
Can we keep it open as I'm not 100% sure that it's fixed I would like to know from @christopheblin that the fixes we added actually fix this problem as my data set is not optimal

**Comment by christopheblin** [comment] 2022-08-23 09:43
Unfortunately, I will not be able to test KC 19 before some time (we have not completed our migration to 18 yet so I suppose we wont use KC 19 at all)

feel free to close this issue if you think that the fixes should be enough, I'll reopen new issues if needed

**Comment by edewit** [comment] 2022-08-24 07:07
Okay then we will close this issue, I've tested it with a lot of groups, don't know for sure but if not we can always revisit this

**Closed by edewit** 2022-08-24 07:07 UTC
Labels: kind/bug, impact/medium, area/section/groups
