### ISSUE TITLE
New Admin UI - Attribute in RO during creation

### ISSUE THREAD

**Issue by Ekouyoja** [keycloak/keycloak-ui#3924] opened 2022-12-02 09:54 UTC
### Describe the bug

- Compile last admin-ui theme
- Activate user profile
- Create new attribute with admin view only

![attribute_permission](https://user-images.githubusercontent.com/16814142/205265578-f5b4f9e2-0292-4784-9426-dc0ef94e606a.png)

- Try to create new user from the admin-ui

![attribute_during_user_creation](https://user-images.githubusercontent.com/16814142/205265618-490a2f8d-a917-4d7d-ae72-a20e36fb409c.png)

- We can see that the attribute is in read only mode also during creation.

It works perfectly on registration page.

### Version

20.0.1

### Environment

Chrome, edge

### Expected behavior

Attribute is editable during the creation on admin-ui

### Actual behavior

Attribute is lock in read-only

**Comment by edewit** [comment] 2022-12-02 11:08
wouldn't you just need to add the 'edit' role to the admin?

**Comment by Ekouyoja** [comment] 2022-12-02 11:49
No because i don't want users or admin modify this attribute once he was created.
It can be the case for username for exemple.

**Comment by jbman** [comment] 2022-12-02 14:04
If an admin is not allowed to edit, create is also not allowed. The attribute could be set by an extension, e.g. an authenticator or mapper.
The problem is, that required attributes need are already required on create. To get what you would like to achieve, Keycloak would need a "required after create" flag per attribute in addition to "required".
The workaround is to set the attribute not generally required but only required for a specific scope. Then the admin can create a user without providing a value.

**Comment by ssilvert** [comment] 2022-12-02 20:47
@Ekouyoja Do you have any objection to closing this issue?

**Comment by Ekouyoja** [comment] 2022-12-03 09:58
If it's the normal behavior, yes you can.
Thank you for the response.

**Closed** 2022-12-03 09:58 UTC
Labels: kind/bug, status/triage, area/admin/ui
