### ISSUE TITLE
Pagination don't work with filtered roles 

### ISSUE THREAD

**Issue by vplemyannik** [keycloak/keycloak-ui#4247] opened 2023-01-23 17:06 UTC
### Describe the bug

Open user and try assign roles to him 
Also reproduced when you trying to assign roles to client scope 
![assign_role](https://user-images.githubusercontent.com/17518385/214103076-68d473ae-67c3-41eb-b682-23c757397dd3.gif)

### Version

20.0.3

### Expected behavior

Pagination works with filtered roles

**Comment by ssilvert** [comment] 2023-01-23 19:42
I believe this is already fixed by https://github.com/keycloak/keycloak-ui/issues/3905

You can check the nightly build to be sure, but I'm going to go ahead and close this issue.  We can reopen if you still find a problem in the nightly build.

https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by vplemyannik** [comment] 2023-01-24 09:44
@ssilvert, thank you for quick reply.  But issues that you have mentioned https://github.com/keycloak/keycloak-ui/issues/3905 pagination don't work at all. But in my case pagination don't work only when there is a value in search input (when roles are filtered). If search input are empty pagination works as expected. And i can reproduce this behavior in 20.0.3 version of keycloak. 
I just want to point that these issues are different.
I dont know how to check with nightly build... i use docker image of keycloak to check

**Comment by ssilvert** [comment] 2023-01-24 11:45
@vplemyannik OK.  I'll take a closer look.

**Comment by jonkoops** [comment] 2023-01-24 13:38
I might be wrong, but I believe this is intentional behavior. I don't believe the REST API supports both pagination and a search query at the same time. @edewit do you happen to know this?

**Comment by edewit** [comment] 2023-01-26 14:55
that's not true it should do both. I'm not able to reproduce this though

**Comment by jonkoops** [comment] 2023-01-26 15:49
I am also not able to reproduce this so I am assuming this was fixed since 20.0.3. Closing this issue.

**Closed by jonkoops** 2023-01-26 15:49 UTC
Labels: kind/bug, status/triage, area/section/users, area/admin/ui
