### ISSUE TITLE
b.map is not a function 

### ISSUE THREAD

**Issue by vplemyannik** [keycloak/keycloak-ui#4576] opened 2023-03-14 09:36 UTC
### Describe the bug

Error when open users on master realm 
![image](https://user-images.githubusercontent.com/17518385/224958545-17b09782-c4a8-483b-9008-3d66dda7f955.png)

Reproduced with nightly build
![image](https://user-images.githubusercontent.com/17518385/224959189-fea7980f-ed2a-42f7-9e31-544ccbbfd504.png)

### Version

nightly

**Comment by vplemyannik** [comment] 2023-03-14 09:42
i have used nightly build to check https://github.com/keycloak/keycloak-ui/issues/4562 issue, but could not open the user page

**Comment by thomasdarimont** [comment] 2023-03-14 10:21
Just hit the same issue with latest nightly

**Comment by thomasdarimont** [comment] 2023-03-14 10:39
It seems as if the findUsers(..) call returns an error object (for a 404) instead of throwing an exception:
![image](https://user-images.githubusercontent.com/314690/224975388-881d40c4-4580-4c80-a1eb-4795d0017a6b.png)

**Comment by thomasdarimont** [comment] 2023-03-14 12:24
I think I found the root cause. It seems that the new admin-console now uses custom endpoints provided via 
[AdminExtProvider.](https://github.com/keycloak/keycloak/blob/main/rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/AdminExtProvider.java). However, this new provider doesn#t seem to be part of the nightly build. When I build the `rest/admin-ui-ext` myself and copy the resulting jar in the providers directory of the Keycloak container, then it works as expected.

**Comment by thomasdarimont** [comment] 2023-03-14 12:53
Created issue https://github.com/keycloak/keycloak/issues/17649 and PR https://github.com/keycloak/keycloak/pull/17650 with a fix in Keycloak upstream.

**Comment by jonkoops** [comment] 2023-03-14 12:57
Closing this issue as we already have another on the main repo. Thanks for investigating this @thomasdarimont.

**Comment by jonkoops** [comment] 2023-03-14 12:58
Duplicate of https://github.com/keycloak/keycloak/issues/17649

**Closed by jonkoops** 2023-03-14 12:58 UTC
Labels: kind/bug, status/triage
