### ISSUE TITLE
Client keys export button is not working in new UI

### ISSUE THREAD

**Issue by santicastro** [keycloak/keycloak-ui#3376] opened 2022-09-21 15:55 UTC
### Describe the bug

Export certificate button in `Clients > [client] > keys > Signing keys config` does nothing in new UI, I have to enable legacy UI to export the certificate

### Version

19.0.2

### Expected behavior

Show export modal

### Actual behavior

Does nothing

### How to Reproduce?

In any client with "client signature required", click "export" button

**Comment by jonkoops** [comment] 2022-09-21 16:18
@santicastro can you confirm this is still an issue for 19.0.2?

**Comment by santicastro** [comment] 2022-09-21 16:46
Yes, I have updated and it is still not working

**Comment by jonkoops** [comment] 2022-09-22 09:31
Thanks for checking, I'm going to see if I can reproduce this issue.

**Comment by jonkoops** [comment] 2022-09-22 09:36
Looks like indeed this button has not been implemented yet, this functionality was missed during our porting.

**Comment by jonkoops** [comment] 2022-11-17 12:16
Resolved by #3648

**Closed by jonkoops** 2022-11-17 12:16 UTC
Labels: kind/bug, priority/important, impact/high, area/section/clients, area/admin/ui
