### ISSUE TITLE
UI Realm/Groups/Group details/Permissions Permissions enabled Off - not possible to enable it.

### ISSUE THREAD

**Issue by lhanusov** [keycloak/keycloak-ui#3293] opened 2022-09-08 14:02 UTC
### Describe the bug

Group fine grained permissions are permanently disabled, not possible to enable it.

![image](https://user-images.githubusercontent.com/61745358/189141253-f9f579d3-ad82-4144-a5f7-19fbc5d705f8.png)

### Version

999-SNAPSHOT

### Expected behavior

Group fine grained permissions enabled - Permissions enabled: On

### Actual behavior

Group fine grained permissions disabled - Permissions enabled: Off

### How to Reproduce?

1. create a new realm with the name A
2. create a new group with the name A
3. Go to the A group tab Groups/Group details/Permissions and turn on the Permissions.

**Comment by ssilvert** [comment] 2022-09-08 18:06
This works fine for me.  You say you are running a snapshot build?  I tried it with the nightly from a couple of days ago and it is working.

**Comment by lhanusov** [comment] 2022-09-12 08:33
@ssilvert Hi Stan, it's installed via keycloak-operator (nightly build) using K8S yml file: https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/refs/tags/nightly/kubernetes/kubernetes.yml, I've even tried it with Firefox or Chrome, it didn't work. Is there any UI restriction? Thank you

**Comment by ssilvert** [comment] 2022-09-28 14:01
I'm going to close as unable to reproduce.  Feel free to comment or reopen if you have further concerns.

**Comment by lhanusov** [comment] 2022-09-29 09:52
@ssilvert As I can see it's a tech-preview feature: https://www.keycloak.org/docs/latest/server_admin/#_fine_grain_permissions, I would rather hide the group permissions tab or add there a hint, why it's blocked. From the usability perspective it's unclear why it behaves so. What do you think?

**Comment by ssilvert** [comment] 2022-09-29 12:55
@lhanusov I agree.  That's a bug.  Thanks.

We need to check other places in the app to make sure that Permissions tab is hidden when `admin-fine-grained-authz` flag is not passed at startup.

**Comment by edewit** [comment] 2022-12-16 13:14
@ssilvert this is fixed now right?

**Comment by ssilvert** [comment] 2023-01-04 18:34
Yes, this is fixed.

**Closed by ssilvert** 2023-01-04 18:34 UTC
Labels: kind/bug, impact/low, area/section/groups, area/admin/ui
