### ISSUE TITLE
[UX Review] Client policies: hovering status of the breadcrumb is not correct

### ISSUE THREAD

**Issue by yih-wang** [keycloak/keycloak-ui#1784] opened 2021-12-23 12:01 UTC
### Describe the bug

Hovering on the 'policy details' will also hover on 'client policies'
![image](https://user-images.githubusercontent.com/23331885/147237645-2d09344b-9d85-4350-bde3-8917d696a3b9.png)

### Version

15.0.2

**Comment by ikhomyn** [comment] 2022-08-17 08:39
Hi,
I tried to reproduce this one, but currently seems it is working as expected
![Untitled](https://user-images.githubusercontent.com/89014675/185074237-983cc40d-e87c-458d-a482-6367a0da223b.png)

**Comment by jonkoops** [comment] 2022-08-22 16:10
Since this is working as expected I am closing this issue.

**Closed by jonkoops** 2022-08-22 16:10 UTC
Labels: kind/bug, area/ux-review, impact/low, area/section/realm settings
