### ISSUE TITLE
unable to open realm settings after update

### ISSUE THREAD

**Issue by wlo** [keycloak/keycloak-ui#3504] opened 2022-10-06 13:14 UTC
### Describe the bug

I updated keycloak 17.0.0 to 19.0.2.
I run `bin/kc.sh build` and `bin/kc.sh start --spi-connections-jpa-default-migration-strategy=update`
Login to master, click on Configure/Realm Settings: `Danger alert:missing name after . operator` 
This alert occurs on every realm - when trying to open realm settings

### Version

19.0.2

### Expected behavior

open realm settings for configuration

### Actual behavior

alert message, complete page refresh is necessary

### Anything else?

very cool and good work.

**Comment by ssilvert** [comment] 2022-10-06 23:22
@wlo I'm not sure how to go about reproducing this.  Are you able to use the old admin console OK?  I realize it might be hard to switch to the old console since you can't open realm settings.  Perhaps use the admin client to explicitly set the admin theme to "keycloak"?

**Comment by wlo** [comment] 2022-10-07 08:10
@ssilvert thanks for your tip, I had to run this cmd for every realm to change from "base" to "keycloak": `kcadm.sh update realms/realmname -s adminTheme=keycloak --server ...`

**Comment by ssilvert** [comment] 2022-10-07 19:06
@wlo What was the result?  Did the old console work OK?  Do you have any more insight on how to recreate your problem?

**Comment by wlo** [comment] 2022-10-11 13:30
the old and the new console are working, just not with the base theme.
I checked on our productive service, this is running with 18.0.0 and the old console. This should be similar to the situation before the update: 
`master-realm
no theme for loginTheme, accountTheme, adminTheme

REALM1
"loginTheme" : "custom",
"accountTheme" : "keycloak.v2",
"adminTheme" : "base",
  
REALM2 - productive
"loginTheme" : "custom",
"accountTheme" : "custom",
"adminTheme" : "base",`

according to show-config there is no profile activated on productive; I am realy sure this was productive after the last update.
I think I will change the adminTheme to keycloak before the update.

**Comment by ssilvert** [comment] 2022-10-11 19:52
@wlo Can we close this issue?

**Comment by wlo** [comment] 2022-10-12 07:12
we can close this.

**Closed** 2022-10-12 07:12 UTC
Labels: kind/bug, status/triage
