### ISSUE TITLE
Frontend white zone after resource deleting

### ISSUE THREAD

**Issue by orcunozbay** [keycloak/keycloak-ui#3439] opened 2022-09-28 13:43 UTC
### Describe the bug

I deleted default resource and then I couldnt see any add button. 

### Version

19.0.2

### Expected behavior

create resource button for first

### Actual behavior

White zone

### How to Reproduce?

Create a client and check authorization. and then delete default resource.

### Anything else?

![Ekran Resmi 2022-09-28 16 41 12](https://user-images.githubusercontent.com/5327418/192795134-a1371622-2352-4e47-8280-3e55577466ec.png)

**Comment by ssilvert** [comment] 2022-09-28 20:56
Hi @orcunozbay.  I could not reproduce this.  I get a default screen with a "Create resource" button.

Perhaps it is already fixed?  Please try the latest nightly build and let us know if you still see the problem.

https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by orcunozbay** [comment] 2022-09-28 22:20
Hi I will try tomorrow. Please check the attachment.
Also I am using as docker container.


https://user-images.githubusercontent.com/5327418/192898765-538c6f55-7f4e-454b-8eba-b74527f3045d.mov

**Comment by edewit** [comment] 2022-09-30 06:02
fixed by: #3366

**Comment by jonkoops** [comment] 2022-09-30 08:21
Duplicate of #3296

**Closed by jonkoops** 2022-09-30 08:21 UTC
Labels: kind/bug, status/triage
