### ISSUE TITLE
Only a few groups visible in admin console

### ISSUE THREAD

**Issue by keerden** [keycloak/keycloak-ui#3496] opened 2022-10-06 08:53 UTC
### Describe the bug

When viewing groups in table mode the keycloak.v2 interface, only a the first 10 groups are displayed and the pagination does not work. When adding subgroups to groups, even less groups are displayed. The groups show up correctly in the tree-view mode.

### Version

19.0.2-legacy

### Expected behavior

When opening the groups page, the groups table is filled with all groups and pagination works.

### Actual behavior

When opening the groups page, the groups table is only filled with 10 groups, pagination does not work. Buttons are greyed out and no other groups are shown when selecting '20 per page' or any other value.  When adding subgroups to groups, even less groups are shown.
![groups_2](https://user-images.githubusercontent.com/6941456/194266392-aa996b3b-e2f9-4972-b446-37086183a1ed.PNG)

### How to Reproduce?

On a fresh keycloak install:
1. create realm
2. goto the groups page of that realm
3. create 15 groups 
4. In the table view on the groups page, only 10 groups are displayed.
5. add 2 subgroups to the first group
6. now only 8 groups are displayed in the overview

**Comment by ssilvert** [comment] 2022-10-06 14:46
Hi @keerden.  We can not pre-load all the groups because in some installations there are thousands of them.

However, we are making big improvements to the groups page and there is already a PR if you want to build and review it.  See:
https://github.com/keycloak/keycloak-ui/issues/3164

The new version of Groups should be included in Keycloak 20.0.0.

I couldn't reproduce the bug you talk about so I'm going to close this.   Maybe it's already fixed?

If you still see issues with the new Groups version, please let us know.

**Closed** 2022-10-06 14:46 UTC
Labels: kind/bug, status/triage
