### ISSUE TITLE
admin2 broken for Idp/mappers and Client scopes

### ISSUE THREAD

**Issue by nxadm** [keycloak/keycloak-ui#3377] opened 2022-09-21 16:22 UTC
### Describe the bug

The new admin interface gives errors when trying to access Identity Providers / Mappers (`"undefined" is not valid JSON`) and Client Scopes / Client Scopes details ( `Expected "type" to be defined`). 

The previous admin console does not have the problems. Disabling on 19.0.1 and 19.0.2 is a workaround.

### Version

19.0.2

### Expected behavior

Being able to edit mappers and scopes.

### Actual behavior

UI error.

### How to Reproduce?

Go to Identity Providers / Mappers and try to add a mapper. Our Identity Providers is a SAML2.

**Comment by ssilvert** [comment] 2022-09-28 00:35
Hi @nxadm.  I cannot reproduce this.  Maybe it's already fixed?

Please try out the latest nightly build at https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by kherock** [comment] 2022-10-04 23:10
There's an issue in Identity Providers / Mappers that I haven't gotten around to reporting yet but this sounds like it's the same one. I think I've seen this present in the admin2 theme since Keycloak 17 - currently on 19.0.2 I get a full screen error when viewing a mapper when it doesn't have `{ attributes: "[]", claims: "[]" }` in the mapper config.

**Comment by ssilvert** [comment] 2022-10-17 18:17
I'm closing this for now.  We can reopen if the issue persists.

**Closed by ssilvert** 2022-10-17 18:17 UTC
Labels: kind/bug, status/triage
