### ISSUE TITLE
When Use JWKS URL is set to on and saved there is no way to see or update the JWKS URL

### ISSUE THREAD

**Issue by doflo-dfa** [keycloak/keycloak-ui#4232] opened 2023-01-19 11:53 UTC
### Describe the bug

The new admin UI seems to block the ability to see the JWKS URLs 

<img width="1188" alt="image" src="https://user-images.githubusercontent.com/77824565/213435535-312fe1df-f9dd-4859-91da-ded300b474ac.png">

### Version

20.0.3

### Environment

Chrome 

### Expected behavior

In prior versions of the admin UI you could update the JWKS URL

### Actual behavior

In the new UI you can not.

### How to Reproduce?

Log in and try to update the JWKS URL

**Comment by ssilvert** [comment] 2023-01-19 21:09
I believe this is a duplicate of https://github.com/keycloak/keycloak-ui/issues/3912, so I'm going to close this one.

It should be fixed in the nightly build or you can wait until Keycloak 21.   We can reopen if you think there is still an issue.

https://github.com/keycloak/keycloak/releases/tag/nightly

**Closed by ssilvert** 2023-01-19 21:09 UTC
Labels: kind/bug, status/triage
