### ISSUE TITLE
No button “Sync LDAP group to Keycloak”

### ISSUE THREAD

**Issue by scydas** [keycloak/keycloak-ui#4317] opened 2023-02-03 01:57 UTC
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

ldap

### Describe the bug

I add group-ldap-mapper into User Federation but Sync button isn’t shown
![image](https://user-images.githubusercontent.com/22952515/216304629-7562b60d-d829-41cb-b9ff-1399cd8958d8.png)

### Version

20.0.1

### Expected behavior

"Sync LDAP group to Keycloak" button is exists and clickable

### Actual behavior

No button “Sync LDAP group to Keycloak”

### How to Reproduce?

Configure the ldap group mapper

**Comment by jonkoops** [comment] 2023-02-03 11:16
@scydas could you verify this problem is also present in the latest [nightly version](https://github.com/keycloak/keycloak/releases/tag/nightly)?

**Comment by ssilvert** [comment] 2023-02-04 02:50
@scydas I do see the `Sync` option on the action menu for `group-ldap-mapper`.  So it seems to be working for me on the latest build.

I don't know of any work in that part of the code lately, but it would be helpful if you could try the nightly build and let us know what you see.

https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by scydas** [comment] 2023-02-04 13:54
I use a docker image：quay.io/keycloak/keycloak:20.0.3
![image](https://user-images.githubusercontent.com/22952515/216770147-f72543a0-ccd8-4f0b-97b9-6fa89f61abac.png)
![image](https://user-images.githubusercontent.com/22952515/216770460-4db60c01-1498-4051-b50e-90aeb12d8b78.png)

the latest nightly version does not have this problem
![image](https://user-images.githubusercontent.com/22952515/216771437-363d2d69-bc41-49e6-9949-8bff56044790.png)

**Comment by ssilvert** [comment] 2023-02-07 19:53
I am seeing the `Sync` actions in the latest code.
<img width="948" alt="group-ldap-mapper" src="https://user-images.githubusercontent.com/507202/217350295-80909db5-bdd6-4ebb-936b-b87905900470.png">

It's possible that your older version wasn't pulling down the correct metadata for the `group-ldap-mapper`.  It is looking for `fedToKeycloakSyncSupported` and `keycloakToFedSupported`.

<img width="954" alt="sync-supported" src="https://user-images.githubusercontent.com/507202/217350841-a23ed394-c3ce-4020-8026-15f90c5c1707.png">

**Comment by scydas** [comment] 2023-02-08 01:57
![image](https://user-images.githubusercontent.com/22952515/217408692-09811965-ca30-4b0d-9e92-47af49f62a4c.png)
the metadate is correct.
Will this issue be fixed in 20.0.4?

**Comment by ssilvert** [comment] 2023-02-08 21:15
@scydas We still haven't determined if there is a bug in the latest source code.  I just know that I can't reproduce it.

Have you been able to try out the nightly build?
https://github.com/keycloak/keycloak/releases/tag/nightly

As for which release a fix will be in, I can't guarantee that any particular fix will be in a patch release.  But all fixes will go into Keycloak 21.

**Comment by edewit** [comment] 2023-02-14 10:59
closing as this has been fixed in the nightly build

**Closed by edewit** 2023-02-14 10:59 UTC
Labels: kind/bug, status/triage, area/section/user federation, area/admin/ui, team/ui
