### ISSUE TITLE
"Assign role to user" - roles beyond first 10 not accessible

### ISSUE THREAD

**Issue by benzitohhh** [keycloak/keycloak-ui#3715] opened 2022-11-04 14:11 UTC
### Area

admin/ui

### Describe the bug

In the "assign role to user" modal (accessed via user -> roles)...

* pagination buttons do nothing (so results stay on the first window of 10 results, and it is not possible to access the rest)

* search box does nothing also

### Version

20.0.0

### Expected behavior

* pagination buttons should move to the next/previous page of results

* search box should return matches

### Actual behavior

* pagination buttons change the page label (i.e. from 1-10 to 11-20 say), but the results for first page are still shown.

* search box does nothing (all results are shown, no filtering)

### How to Reproduce?

In Keycloak admin UI...

Ensure there are more than 10 realm roles.

* click Users tab (left sidebar)

* click on a User

* click the "Role mapping" tab

* click the "Assign role" button

* In the modal: try clicking the pagination buttons and/or using the search box

**Comment by ssilvert** [comment] 2022-11-04 16:31
@benzitohhh This should be fixed in the latest nightly build.  Can you try it out and let us know?

https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by ssilvert** [comment] 2022-11-07 14:16
https://www.keycloak.org/server/configuration#_starting_keycloak

**Comment by benzitohhh** [comment] 2022-11-07 15:59
Sorry @ssilvert I'm still totally confused how to run the nightly build :(

The link you sent (https://github.com/keycloak/keycloak/releases/tag/nightly) has bunch of zip files - which of these contains the actual build?

When I looked, most of the zip files just contain jar files, so I'm not sure how to start the server from these.

Thanks!

**Comment by ssilvert** [comment] 2022-11-07 16:30
If you want to use the zip file, just unzip [keycloak-999-SNAPSHOT.zip](https://github.com/keycloak/keycloak/releases/download/nightly/keycloak-999-SNAPSHOT.zip).

I run it like this:
`cd lib`
`java -jar quarkus-run.jar start-dev`

**Comment by benzitohhh** [comment] 2022-11-07 16:41
Ah thanks @ssilvert - I think that `keycloak-999-SNAPSHOT.zip` file was not there before.

Ok when I run that as per your instuctions, I get:
```
java -jar quarkus-run.jar start-dev
2022-11-07 16:39:23,244 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin URL: <unset>, Admin: <request>, Port: -1, Proxied: false
2022-11-07 16:39:24,426 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': Connector/J cannot handle a connection string 'jdbc:h2:file:/Users/benimmanuel/data/h2/keycloakdb;;AUTO_SERVER=TRUE'.
2022-11-07 16:39:24,427 WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread: keycloak-default) HHH000342: Could not obtain connection to query metadata: java.sql.SQLException: Connector/J cannot handle a connection string 'jdbc:h2:file:/Users/benimmanuel/data/h2/keycloakdb;;AUTO_SERVER=TRUE'.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:131)
	at com.mysql.cj.jdbc.MysqlDataSource.getConnection(MysqlDataSource.java:128)
	at com.mysql.cj.jdbc.MysqlDataSource.getConnection(MysqlDataSource.java:113)
	at com.mysql.cj.jdbc.MysqlXADataSource.getXAConnection(MysqlXADataSource.java:52)
	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:232)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:535)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:516)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)

2022-11-07 16:39:24,710 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2022-11-07 16:39:24,778 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2022-11-07 16:39:24,791 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2022-11-07 16:39:24,937 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.10.Final
2022-11-07 16:39:25,166 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: node_334341, Site name: null
2022-11-07 16:39:25,169 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': Connector/J cannot handle a connection string 'jdbc:h2:file:/Users/benimmanuel/data/h2/keycloakdb;;AUTO_SERVER=TRUE'.
2022-11-07 16:39:25,312 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (development) mode
2022-11-07 16:39:25,312 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to obtain JDBC connection
2022-11-07 16:39:25,313 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Connector/J cannot handle a connection string 'jdbc:h2:file:/Users/benimmanuel/data/h2/keycloakdb;;AUTO_SERVER=TRUE'.
2022-11-07 16:39:25,313 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```

**Comment by ssilvert** [comment] 2022-11-07 19:01
You might be running into this problem if you are on Windows.  You will need to wait until tomorrow to get the fix.
https://github.com/keycloak/keycloak/pull/15376

**Comment by benzitohhh** [comment] 2022-11-07 19:14
ah ok, I'm actually on MacOS, but will check tomorrow - thanks

**Comment by ssilvert** [comment] 2022-11-14 13:42
@benzitohhh Did you ever get a chance to check this out?

**Comment by benzitohhh** [comment] 2022-11-14 13:58
Hey @ssilvert I just tried the latest nightly build (https://github.com/keycloak/keycloak/releases/download/nightly/keycloak-999-SNAPSHOT.zip)

But the issue is still there. See screenshot below.

It is really easy to reproduce (see the instructions at the beginning of this issue).

<img width="1443" alt="Screenshot 2022-11-14 at 13 55 15" src="https://user-images.githubusercontent.com/861758/201678437-992112d7-3e90-4e3a-ae74-8bede71fd9fb.png">

**Comment by ssilvert** [comment] 2022-11-15 20:38
Thanks @benzitohhh.  Looks like you are not the only one reporting this.  It was just fixed today.  I'm closing as a duplicate of https://github.com/keycloak/keycloak-ui/issues/3740

**Closed by ssilvert** 2022-11-15 20:38 UTC
Labels: kind/bug, status/triage, area/admin/ui

**Comment by benzitohhh** [comment] 2022-11-16 09:43
@ssilvert Ah ok thanks much appreciated
